# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AcMilanApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AcMilanApplication
	pod 'Alamofire', '~> 5.4'
	pod 'Kingfisher', '~> 6.0'
	pod 'SnapKit', '~> 5.0.0'
	pod 'RxSwift', '~> 5.1'
  	pod 'RxCocoa', '~> 5.1'
	pod 'DropDown'
	pod 'Toast-Swift', '~> 5.0.1'
end
